# -*- coding: utf-8 -*-
"""1D_Convolution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19uxcxKOC7-Rr9C0yWrYdoFCq4rbeSZ7z
"""

import numpy as np
import matplotlib.pyplot as plt

signal = np.array([1, 1, 1, 0.5, 0.5, 1, 1, 0.5, 0.5, 0.5])

plt.stem(signal)
plt.show()

filter = np.array([-1, 1])

result = np.convolve(signal, filter, 'valid')

plt.stem(result)
plt.show()

