# -*- coding: utf-8 -*-
"""Image_Filtering_(Convolution)- Test 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zTJvfbL2FVg50iwXh4aD4fgxWJ9jze3-
"""

import cv2
from matplotlib import pyplot as plt
import numpy as np



"""### Load the image using OpenCV"""

im = cv2.imread('/content/sample_data/lenna.png')
plt.imshow(im)

im.shape

"""### Convert the RGB image into a grayscale image"""

im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
im.shape
plt.imshow(im)

"""### Define vertical and horizontal filter kernels"""

h_kernel = np.array([

       [-1, -1, -1],

       [0, 0, 0],

       [1, 1, 1]

])



"""### Do the filtering"""

h_image = cv2.filter2D(im, -1, h_kernel)
plt.imshow(h_image)

"""### Display results"""

plt.imshow(im, cmap='gray')
plt.title('Original Image')

plt.figure()

plt.imshow(h_image, cmap='gray')

plt.title('Horizontal Image')